
@protocol = http
@hostname = localhost
@port = 3000
@host = {{protocol}}://{{hostname}}:{{port}}
@prefix = api
@apiHost = {{host}}/{{prefix}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###

GET {{apiHost}}/hello HTTP/1.1
Content-Type: {{contentType}}

###

GET {{apiHost}}/weather?id=abc HTTP/1.1
Content-Type: {{contentType}}

###

GET {{apiHost}}/safety/gender HTTP/1.1
Content-Type: {{contentType}}

###

GET {{apiHost}}/safety/gender-shift HTTP/1.1
Content-Type: {{contentType}}
